### ISSUE TITLE
Empty text-box does not resize

### ISSUE THREAD

**Issue by barmac** [bpmn-io/diagram-js-direct-editing#12]
__Describe the Bug__

Element bounds are unstable when resizing a text field created by direct editing.

__Steps to Reproduce__

* Create a text annotation.
* Open direct editing of the created element.
* Without typing, resize the text input.
* Complete direct editing (with no text entered)
* __The box bounds jump back to the original size__

__Expected Behavior__

* [ ] Text annotation should be resized to new bounds

__Screencast__

![bug](https://user-images.githubusercontent.com/58601/55710375-cbec6f80-59ea-11e9-8816-48a5fba0edb7.gif)

__Environment__

Please complete the following information:

 - Browser: Chromium (Camunda Modeler)
 - OS: MacOS
 - Library version: 1.14.1

**Comment by nikku** [comment]
What is your expected behavior? It is not clear to me, looking at the screen cast alone.

**Comment by barmac** [comment]
I added a text description.

**Comment by nikku** [comment]
Got it, thanks for clarifying. :+1:

**Comment by nikku** [comment]
Actually a bug downstream, fixed via https://github.com/bpmn-io/bpmn-js/pull/1290.
