### ISSUE TITLE
Force update

### ISSUE THREAD

**Issue by tim-kilian** [bpmn-io/diagram-js-direct-editing#15]
## Problem

The following if statement is causing some weird behavior because the update is not triggered initially. We would like to have some options to forceUpdate to initialize our component.

https://github.com/bpmn-io/diagram-js-direct-editing/blob/81dde32364212952c5078956d6a7fcc56a1677fb/lib/DirectEditing.js#L96-L100

**Comment by nikku** [comment]
Could you elaborate on your use case? Why would you ever want to force an update _if nothing changed_?

**Comment by tim-kilian** [comment]
Because our update procedure have some logic that is positioning the label. If we try to initialize or import the label with some default value it is misplaced. I contrariwise do not see any sense in not calling an update in the complete call.

**Comment by nikku** [comment]
Could you layout your case in a bit more detail?

I do not see how updating the label should be necessary for placing it in an appropriate spot.

**Comment by nikku** [comment]
> I contrariwise do not see any case where you dont want to call an update during the complete call.

Adds more stuff to the undo queue, despite the fact that nothing has happened.

**Comment by nikku** [comment]
Closing this issue and the related PR due to missing input.

We are happy to revive this one, if you layout your case in the required detail.

:heart:  from the team!
