### ISSUE TITLE
Push 1.6.4 to npmjs

### ISSUE THREAD

**Issue by rostigerloeffel** [bpmn-io/diagram-js-direct-editing#22]
__What should we do?__

Push version 1.6.4 to npmjs.com.

__Why should we do it?__

To make diagramjs 8.x installable together with diagram-js-direct-editing.

**Comment by pinussilvestrus** [comment]
Seems like we updated the changelog but did not finalize the release. I just pushed it: https://www.npmjs.com/package/diagram-js-direct-editing/v/1.6.4

Thanks for letting us know!

**Comment by rostigerloeffel** [comment]
Works perfectly fine now! Thanks a lot for the quick fix!
