### ISSUE TITLE
Direct editing box hides underlying element

### ISSUE THREAD

**Issue by nikku** [bpmn-io/diagram-js-direct-editing#23]
__Is your feature request related to a problem? Please describe__

As I'm editing an element the actual element is hidden by the direct editing box. This is a source of confusion, especially as elements are being created with a particular item (i.e. a service task) and the icon not being visible. 

![capture ZBnvzY_optimized](https://user-images.githubusercontent.com/58601/159492189-36217800-b542-4fc9-97da-751b21798cfe.gif)

As an improvement I suggest hiding the direct editing background. This improves the editing experience for internal labels, as far as I believe. Not sure if the impact on external labels is a positive one, though:

![capture RfRN0f_optimized](https://user-images.githubusercontent.com/58601/159492474-494df529-fe9c-4648-8e24-7cf7ae2a2a1e.gif)

__Describe the solution you'd like__

* [ ] Direct editing box does not hide element it is editing (unless explicitly configured)

__Describe alternatives you've considered__

I can override the relevant styles via `!important` CSS.

__Additional context__

This came up in multiple occasions in the context of our element template / connectors work.

**Comment by nikku** [comment]
> How much do we already know about that? Did this pop up during user tests?

It popped up twice during two user tests (web-modeler QA + another one).

**Comment by christian-konrad** [comment]
I really found the editing box confusing (it is hard to distinguish from the task itself, therefore it looks like the task turned into a rectangle).
If this is a low-hanging fruit to just make the box transparent, we should do it, especially as the box does not even resize when text is overflowing.

**Comment by currandwyer** [comment]
These overflows are generally something of an annoyance, as when you have 3+ lines in the title, the (eg. user task) icon can be overlapping. I think hiding the edit box removes a bit of context and feedback on what's happening, almost feeling like a bug - and definitely like a bug with external labels. However, the icon persisting and overlapping the editing box feels like an improvement. Would it be possible to add an opacity (say, 70%) to the editing box so that the icon still appears, but is muted?

**Comment by nikku** [comment]
Moving to backlog. Unless we come up with something clever we'll not be able to immediately act on it. @currandwyer consider make up your mind on the desired interaction in BPMN land, considering all options (internal, external, text annotation, participant, (expanded) sub-process label editing.

**Comment by christian-konrad** [comment]
We should consider this again once we implement "Append anything".
Reason: After appending a new dedicated task with the new append anything palette, the input is immediately focused, hiding the icon of the task - which may seem confusing and makes the user ask him/herself "has my selection been right?"

**Comment by marstamm** [comment]
Proposal: The box offers no additional value to the user, unless it is resizable. The underlying element should be enough of a border and the blinking cursor is the indicator for editing.
![image](https://github.com/bpmn-io/diagram-js-direct-editing/assets/21984219/499a73bd-7991-4167-9218-7e927f312b14)

We can keep the background for resizable elements, as we use it without a clear boundary.

![image](https://github.com/bpmn-io/diagram-js-direct-editing/assets/21984219/a884798c-5d8e-4f23-806d-6650139efb43)

Alternatively, we should evaluate if resizing is actually a feature we want and need to support, as it seems to be broken when I was testing it and we already have an (external) way to resize labels.

![Recording 2024-04-18 at 11 15 09](https://github.com/bpmn-io/diagram-js-direct-editing/assets/21984219/2e7b4540-ebad-4b9e-b33e-c213884462db)

**Comment by marstamm** [comment]
Moving to ready as this was brought up multiple times in recently:

https://github.com/camunda/improved-canvas/pull/59#issuecomment-2061581429
https://github.com/camunda/web-modeler/issues/8477
